version: '3.2'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq-queue'
    ports:
      - 5672:5672
      - 15672:15672
    # networks:
    #   - rabbitmq_network
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  
  consumer:
    image: celery-consumer:0.0.1
    restart: always
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    
  producer:
    image: celery-producer:0.0.1
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - consumer
  
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=pyamqp://user:password@rabbitmq:5672
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq
  

# networks:
#   rabbitmq_network:
#     driver: bridge